# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - socialfood

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build_and_deploy_static_web:
    runs-on: ubuntu-latest
    name: Build and Deploy static web
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: App Settings Variable Substitution Web
        uses: microsoft/variable-substitution@v1
        with:
          files: 'SocialFood.Web/wwwroot/appsettings.json'
        env:
          ApiUrl: ${{ secrets.APIURL }}

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_MOSS_0BF03E903 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "SocialFood.Web" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "wwwroot" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  build_api_service:
    runs-on: ubuntu-latest
    name: Build API Service

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      #substitute production appsettings entries to appsettings json file
      - name: App Settings Variable Substitution Server
        uses: microsoft/variable-substitution@v1
        with:
          files: 'SocialFood.API/appsettings.json'
        env:
          JwtSettings.SecurityKey: ${{ secrets.JWTSECURITYKEY }}
          ConnectionStrings.MySQL: ${{ secrets.MYSQL }}
          ConnectionStrings.StorageConnection: ${{ secrets.AZURESTORAGE }}
          AppSettings.ContainerName: ${{ secrets.CONTAINERNAME }}
          NotificationSettings.PrivateKey: ${{ secrets.NOTIFICATION_PRIVATE_KEY }}

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish Server API
        run: |
          cd SocialFood.API
          dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
          cd ..
          cd SocialFood.Data
          dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
          cd ..
          cd SocialFood.Shared
          dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
          cd ..
          cd SocialFood.StorageProviders
          dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
          cd ..

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build_api_service
    name: Publish API Service
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'socialfoodapi'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_96980AB9D3F444778A7447D424260201 }}
          package: .
